services:
  pg_tileserv:
    image: pramsey/pg_tileserv:20240312
    container_name: pg_tileserv
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pg_tileserv_db/tileserv
    depends_on:
      - pg_tileserv_db
    ports:
      - "8080:7800"
    restart: always

  pg_tileserv_db:
    image: postgis/postgis:15-3.4
    container_name: pg_tileserv_db
    command: postgres -c default_statistics_target=100 -c max_connections=100 -c max_locks_per_transaction=64 -c checkpoint_timeout=30min -c maintenance_work_mem=1GB -c effective_cache_size=16GB -c work_mem=500MB -c max_wal_size=10GB -c wal_buffers=16MB -c shared_buffers=8GB
    volumes:
      - pg_tileserv_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tileserv
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      # localの5432が塞がっていると超ハマるので注意
      - "0.0.0.0:54321:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_tileserv_db:
